### PR TITLE
Add CD job for deployment through gitlab

### LINKED ISSUE #22: Add CI/CD and Tests
As the project grows, we need a way to make sure it is easy to test incoming PRs instead of me manually pulling and testing everything. The best way would be to setup a CI/CD pipeline using Github Actions. At the present moment we don't have any tests except the one introduced in #21. Ideally I would like to setup tests and then a CI/CD pipeline. However, the server running the website right now, is manually using cron jobs. I would instead like to wait for #16 to finish and then create a pipeline with the docker image.

Meanwhile, feel free to add tests and help me write a CI pipeline.

### PR DESCRIPTION
**Pull request by GabrieleCalarota**
Related to #50 
Fixes #22

### CODE REVIEW

**Comment by DomiiBunn** [comment]
And we're sure it will just run deploy only on master?

**Comment by DomiiBunn** [comment]
So I don't see an error and it certainly didn't trigger the gitlab CI
https://github.com/kinshukdua/LiveActionMap/runs/5413715608?check_suite_focus=true
These ware triggered by hand sadly
image

**Comment by GabrieleCalarota** [comment]
These are the logs of the github actions:

image

**Comment by GabrieleCalarota** [comment]
So the github actions and triggers are working fine, at the right moment

**Comment by DomiiBunn** [comment]
All i know is that using curl it triggers gitlabs ci with no issue and i don't understand anything from the log

**Comment by edubacco** [comment]
Have you tried adding `debug: true` input variable to the action configuration to see if it logs something useful?

If you have a working curl call, probably it's easier to just [use that command](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun) instead of using an external action (remember to use github secrets)

**Comment by DomiiBunn** [comment]
Can I ask you really nicely if you could pr a change to use curl? I'm really green if it comes to GitHub ci

```bash
curl --request POST "https://gitlab.example.com/api/v4/projects/34155787/trigger/pipeline?token=<token>&ref=main"
```

The token env is `GITLAB_TOKEN`

I hope it will be hidden in the ci it's self

**Pull request merged**
